version: '3.8'

services:
  android-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - gradle-cache:/root/.gradle
    working_dir: /workspace
    command: sleep infinity
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

volumes:
  gradle-cache: